services:

  api:
    build: ./api
    image: ppn-api:latest
    labels:
      - "traefik.http.routers.api.rule=Host(`projects-api.pointbeing.net`, `projects-api.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build: ./site
    image: ppn-site:latest
    labels:
      - "traefik.http.routers.web.rule=Host(`projects.pointbeing.net`, `projects.localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=5001"
    ports:
      - "5001:5001"
    depends_on:
      - api
    restart: unless-stopped

  # traefik:
  #   image: traefik:v2.10
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
