
services:
  api:
    build: ./api
    image: ppn-api:latest
    volumes:
    - ./api:/app
    working_dir: /app
    ports:
      - "5000:5000"
    command: gunicorn main:app --workers 1 --bind 0.0.0.0:5000 --reload

  site:
    build:
      context: ./site
      dockerfile: Dockerfile.dev
    image: ppn-site:latest
    volumes:
    - ./site:/app
    working_dir: /app
    ports:
      - "5001:5001"
    depends_on:
      - api
    command: npm run dev

  # sqlite-web:
  #   image: coleifer/sqlite-web:latest
  #   container_name: ppn-sqlite-web
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./api/instance/projects.db:/data/projects.db
  #   environment:
  #     - SQLITE_DATABASE=/data/projects.db
  #   restart: unless-stopped

  sqlite-web:
    build:
      context: ../sqlite-web
      dockerfile: docker/Dockerfile
    container_name: ppn-sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./api/instance/projects.db:/data/projects.db
      - ../sqlite-web:/app   # mounts local code
    environment:
      - SQLITE_DATABASE=/data/projects.db
    restart: unless-stopped
    command: ["python", "/app/sqlite_web/sqlite_web.py", "--host", "0.0.0.0", "--debug", "/data/projects.db"]
